In [1]:
import numpy as np

Create a null vector of size 10 but the fifth value which is 1.

In [2]:
z = np.zeros(10,dtype=int)
z[4]=1
z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

Create a vector with values ranging from 10 to 49.

In [3]:
v=np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
m_a = np.random.randint(0,9,(3,3))
m_a

array([[5, 8, 4],
       [5, 2, 3],
       [6, 1, 5]])

Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)